// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://daciwcjvddkcnwqybwxn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRhY2l3Y2p2ZGRrY253cXlid3huIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE4OTM3ODQsImV4cCI6MjA2NzQ2OTc4NH0.Yc91YvDAcun8tRezGRasv8gg5E0jlsZrpyeQ-9SpmY4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});